### ISSUE TITLE
Performance tests return a failed state

### ISSUE THREAD

**Issue by dkotter** [swissspidy/wp-performance-action#224]
This is almost certainly an issue on my end but in trying to get this set up today to test on a project, this Action always returns a failed state:

<img width="1133" alt="Failed output" src="https://github.com/user-attachments/assets/0bd2d5b1-82ee-4a9d-96d9-97fbd86c6020" />

Any guidance on debugging this would be great. I tried setting `debug: true` in our workflow to see if I could get more information on what is failing but that then causes the [`Install Playwright browsers`](https://github.com/swissspidy/wp-performance-action/blob/main/action.yml#L112-L119) step to fail with the following: `npm error could not determine executable to run`.

Unfortunately this is on a private repo so I can't link to it but happy to provide any details that would help. Have a pretty basic blueprint and workflow right now to try and get things running but can provide those if that helps.

**Comment by dkotter** [comment]
Here's the two files we're using (lightly trimmed to remove a few things), if that helps:

`performance-benchmark.yml`

```yml
name: Performance Benchmark

on:
  pull_request:
    branches:
      - trunk

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Node cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Node install
        run: npm ci

      - name: Build
        run: npm run build:dev

      - name: Run performance tests
        uses: swissspidy/wp-performance-action@v2
        with:
          urls: |
            /
            /wp-admin/
          plugins: |
            ./
          blueprint: ./.github/workflows/performance-blueprint.json
          iterations: 5
          repetitions: 1
```

`performance-blueprint.json`

```json
{
	"$schema": "https://playground.wordpress.net/blueprint-schema.json",
	"plugins": [
		"woocommerce",
		"email-log"
	],
	"extraLibraries": [
		"wp-cli"
	],
	"steps": [
		{
			"step": "defineWpConfigConsts",
			"consts": {
				"WP_DEBUG": true,
				"WP_CACHE": true
			}
		},
		{
			"step": "activatePlugin",
			"pluginName": "WooCommerce",
			"pluginPath": "/wordpress/wp-content/plugins/woocommerce"
		},
		{
			"step": "activatePlugin",
			"pluginName": "Email Log",
			"pluginPath": "/wordpress/wp-content/plugins/email-log"
		},
		{
			"step": "installTheme",
			"themeZipFile": {
				"resource": "url",
				"url": "https://downloads.wordpress.org/theme/storefront.zip"
			},
			"ifAlreadyInstalled": "skip",
			"options": {
				"activate": true,
				"importStarterContent": false
			}
		},
		{
			"step": "login",
			"username": "admin"
		}
	]
}
```

In addition to the debug problem mentioned, here's a few other things we've run into:

1. For the `installTheme` step, tried to use the latest syntax there but it causes problems. I have to use `themeZipFile` instead of `themeData`. I'm assuming the Action here is using an older version of the Playground code
2. The `login` step doesn't work if set to `true`. Instead you have to explicitly have `"step": "login"` for it to work. This may be the same issue as above, using an older version of Playground
